name: "Tests"
on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - release-*
jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v23
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          accept-flake-config = true
    - name: Build
      run: nix develop -c bash -c 'meson build && cd build && ninja'
    - name: Run tests
      run: nix develop -c pytest ./tests
